// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    BluetoothPrinter: typeof import('./src/components/BluetoothPrinter/index.vue')['default']
    DeliNavbar: typeof import('./src/components/DeliNavbar/index.vue')['default']
    DeliOrder: typeof import('./src/components/DeliOrder/index.vue')['default']
    DeliTabbar: typeof import('./src/components/DeliTabbar/index.vue')['default']
    DeliView: typeof import('./src/components/DeliView/index.vue')['default']
    NutButton: typeof import('@nutui/nutui-taro')['Button']
    NutCell: typeof import('@nutui/nutui-taro')['Cell']
    NutCheckbox: typeof import('@nutui/nutui-taro')['Checkbox']
    NutCol: typeof import('@nutui/nutui-taro')['Col']
    NutCountdown: typeof import('@nutui/nutui-taro')['Countdown']
    NutDivider: typeof import('@nutui/nutui-taro')['Divider']
    NutEmpty: typeof import('@nutui/nutui-taro')['Empty']
    NutInput: typeof import('@nutui/nutui-taro')['Input']
    NutNavbar: typeof import('@nutui/nutui-taro')['Navbar']
    NutPicker: typeof import('@nutui/nutui-taro')['Picker']
    NutPopover: typeof import('@nutui/nutui-taro')['Popover']
    NutPopup: typeof import('@nutui/nutui-taro')['Popup']
    NutPrice: typeof import('@nutui/nutui-taro')['Price']
    NutProgress: typeof import('@nutui/nutui-taro')['Progress']
    NutRow: typeof import('@nutui/nutui-taro')['Row']
    NutTabbar: typeof import('@nutui/nutui-taro')['Tabbar']
    NutTabbarItem: typeof import('@nutui/nutui-taro')['TabbarItem']
    NutTabPane: typeof import('@nutui/nutui-taro')['TabPane']
    NutTabs: typeof import('@nutui/nutui-taro')['Tabs']
    NutTimeDetail: typeof import('@nutui/nutui-taro')['TimeDetail']
    NutTimePannel: typeof import('@nutui/nutui-taro')['TimePannel']
    NutTimeSelect: typeof import('@nutui/nutui-taro')['TimeSelect']
    OrderItem: typeof import('./src/components/DeliOrder/components/OrderItem.vue')['default']
    OrderView: typeof import('./src/components/DeliOrder/components/OrderView.vue')['default']
  }
}
